export default [
  {
    id: 1,
    title: 'Легенды Дагестана',
    description: 'Культурный тур по горным аулам, старинным мечетям и живописным ущельям.',
    price: 40000,
    location: 'Россия',
    travelType: 'экскурсионный',
    images: ['/assets/dagestan.jpg'],
  },
  {
    id: 2,
    title: 'Путешествие по Алтаю',
    description: 'Экспедиция к Телецкому озеру, Чуйскому тракту и горам Белухи.',
    price: 60000,
    location: 'Россия',
    travelType: 'активный',
    images: ['/assets/belucha.jpg'],
  },
  {
    id: 3,
    title: 'Острова Японии',
    description: 'Тур по Токио, Киото и горячим источникам Хоккайдо.',
    price: 120000,
    location: 'Азия',
    travelType: 'экскурсионный',
    images: ['/assets/kyoto.jpg'],
  },
  {
    id: 4,
    title: 'Вино и замки Тосканы',
    description: 'Гастрономическое путешествие по винодельням Италии.',
    price: 90000,
    location: 'Европа',
    travelType: 'гастрономический',
    images: ['/assets/tuscany.jpg'],
  },
  {
    id: 5,
    title: 'Канадские скалистые горы',
    description: 'Походы, озера и дикая природа Британской Колумбии.',
    price: 110000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/rockies_in_the_morning.jpg'],
  },
  {
    id: 6,
    title: 'Карибский круиз',
    description: '7-дневное путешествие по островам с белыми пляжами.',
    price: 130000,
    location: 'Америка',
    travelType: 'пляжный',
    images: ['/assets/caribs.jpg'],
  },
  {
    id: 7,
    title: 'По следам Золотого кольца',
    description: 'Культурный маршрут по древним городам России.',
    price: 35000,
    location: 'Россия',
    travelType: 'экскурсионный',
    images: ['/assets/rostov.jpg'],
  },
  {
    id: 8,
    title: 'Арктическое сафари: Земля Франца-Иосифа',
    description: 'Экспедиция на ледоколе в заполярные широты.',
    price: 150000,
    location: 'Россия',
    travelType: 'экстрим',
    images: ['/assets/franz.jpg'],
  },
  {
    id: 9,
    title: 'Байкал: магия льда и шаманов',
    description: 'Зимнее путешествие по самому глубокому озеру планеты.',
    price: 55000,
    location: 'Россия',
    travelType: 'активный',
    images: ['/assets/baikal.jpg'],
  },
  {
    id: 10,
    title: 'Кавказское гостеприимство',
    description: 'Гастротур в Осетию и Чечню с посещением местных семей.',
    price: 40000,
    location: 'Россия',
    travelType: 'гастрономический',
    images: ['/assets/ossetia.jpg'],
  },
  {
    id: 11,
    title: 'Карелия: отдых в стиле hygge',
    description: 'Уютные домики, озёра и сосновые леса.',
    price: 38000,
    location: 'Россия',
    travelType: 'семейный',
    images: ['/assets/karelia.jpg'],
  },
  {
    id: 12,
    title: 'Москва-ретро',
    description: 'Экскурсии по столице на «Волге» с посещением культовых мест.',
    price: 20000,
    location: 'Россия',
    travelType: 'экскурсионный',
    images: ['/assets/moscow.jpg'],
  },
  {
    id: 13,
    title: 'Камчатка: вулканы и горячие источники',
    description: 'Тур для искателей приключений.',
    price: 90000,
    location: 'Россия',
    travelType: 'экстрим',
    images: ['/assets/kamchatka.png'],
  },
  {
    id: 14,
    title: 'Санкт-Петербург: белые ночи',
    description: 'Романтика и история северной столицы летом.',
    price: 25000,
    location: 'Россия',
    travelType: 'романтический',
    images: ['/assets/saint_petersburg.jpg'],
  },
  {
    id: 15,
    title: 'Тува: шаманские практики и степь',
    description: 'Духовный туризм в глубинке Азии.',
    price: 70000,
    location: 'Россия',
    travelType: 'духовный',
    images: ['/assets/tuva.jpg'],
  },
  {
    id: 16,
    title: 'Япония: цветение сакуры',
    description: 'Весеннее путешествие по храмам и садам.',
    price: 120000,
    location: 'Азия',
    travelType: 'экскурсионный',
    images: ['/assets/sakura.jpg'],
  },
  {
    id: 17,
    title: 'Вьетнам: путь от Ханоя до Сайгона',
    description: 'Морской и наземный тур по всей стране.',
    price: 80000,
    location: 'Азия',
    travelType: 'экскурсионный',
    images: ['/assets/hanoi.jpg'],
  },
  {
    id: 18,
    title: 'Бали: серфинг и медитации',
    description: 'Неделя расслабленного отдыха и практик.',
    price: 75000,
    location: 'Азия',
    travelType: 'пляжный',
    images: ['/assets/bali.jpg'],
  },
  {
    id: 19,
    title: 'Непал: треккинг к Эвересту',
    description: 'Тур с гидами и невероятными пейзажами.',
    price: 95000,
    location: 'Азия',
    travelType: 'активный',
    images: ['/assets/everest.jpg'],
  },
  {
    id: 20,
    title: 'Индия: Гоа и священные города',
    description: 'Пляжи и паломничество.',
    price: 65000,
    location: 'Азия',
    travelType: 'духовный',
    images: ['/assets/goa.jpg'],
  },
  {
    id: 21,
    title: 'Китай: Пекин и Великая стена',
    description: 'История, храмы и кухня.',
    price: 88000,
    location: 'Азия',
    travelType: 'экскурсионный',
    images: ['/assets/great-wall.jpg'],
  },
  {
    id: 22,
    title: 'Таиланд: храмы, острова и массажи',
    description: 'Культурный и пляжный отдых.',
    price: 68000,
    location: 'Азия',
    travelType: 'пляжный',
    images: ['/assets/thailand.jpg'],
  },
  {
    id: 23,
    title: 'Шри-Ланка: чайные плантации и океан',
    description: 'Экзотика и незабываемые виды.',
    price: 80000,
    location: 'Азия',
    travelType: 'гастрономический',
    images: ['/assets/sri-lanka.jpg'],
  },
  {
    id: 24,
    title: 'Греция: Афины и Крит',
    description: 'Мифология и античные памятники.',
    price: 90000,
    location: 'Европа',
    travelType: 'экскурсионный',
    images: ['/assets/greece.jpg'],
  },
  {
    id: 25,
    title: 'Франция: Прованс и Лазурный берег',
    description: 'Гастрономия и французская культура.',
    price: 85000,
    location: 'Европа',
    travelType: 'гастрономический',
    images: ['/assets/nice.jpg'],
  },
  {
    id: 26,
    title: 'Швейцария: Альпы и озера',
    description: 'Горные походы и круизы по озёрам.',
    price: 110000,
    location: 'Европа',
    travelType: 'активный',
    images: ['/assets/swiz.jpg'],
  },
  {
    id: 27,
    title: 'Италия: Рим и Венеция',
    description: 'Экскурсия по величайшим памятникам истории.',
    price: 80000,
    location: 'Европа',
    travelType: 'экскурсионный',
    images: ['/assets/swiz.jpg'],
  },
  {
    id: 28,
    title: 'Испания: Барселона и Тосканские пляжи',
    description: 'Гастрономия и релакс на пляже.',
    price: 85000,
    location: 'Европа',
    travelType: 'пляжный',
    images: ['/assets/barcelona.jpg'],
  },
  {
    id: 29,
    title: 'Португалия: Лиссабон и Алгарве',
    description: 'Культура, пляжи и вино.',
    price: 75000,
    location: 'Европа',
    travelType: 'пляжный',
    images: ['/assets/portugal.jpg'],
  },
  {
    id: 30,
    title: 'Норвегия: фьорды и северное сияние',
    description: 'Экспедиция на лодке по фьордам и наблюдение за северным сиянием.',
    price: 120000,
    location: 'Европа',
    travelType: 'активный',
    images: ['/assets/norway.jpg'],
  },
  {
    id: 31,
    title: 'Австралия: Большой Барьерный риф',
    description: 'Дайвинг и пляжный отдых в одном из чудес природы.',
    price: 150000,
    location: 'Австралия',
    travelType: 'пляжный',
    images: ['/assets/australia.jpg'],
  },
  {
    id: 32,
    title: 'Перу: Мачу-Пикчу и Амазонка',
    description: 'Исторический тур по древним инкским руинам.',
    price: 125000,
    location: 'Америка',
    travelType: 'экскурсионный',
    images: ['/assets/peru.jpg'],
  },
  {
    id: 33,
    title: 'Мексика: Канкун и Чичен-Ица',
    description: 'Пляжи и майянские руины.',
    price: 95000,
    location: 'Америка',
    travelType: 'пляжный',
    images: ['/assets/itza.jpg'],
  },
  {
    id: 34,
    title: 'Аргентина: Патагония и Буэнос-Айрес',
    description: 'Тур по ледникам и культурным столицам Южной Америки.',
    price: 140000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/patagonia.jpg'],
  },
  {
    id: 35,
    title: 'Чили: Вальпараисо и Анды',
    description: 'Пешие походы и отдых на побережье.',
    price: 110000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/andes.jpg'],
  },
  {
    id: 36,
    title: 'США: Национальные парки и Гранд-Каньон',
    description: 'Пешие прогулки по каньонам и пустыням США.',
    price: 150000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/grand_canyon.jpg'],
  },
  {
    id: 37,
    title: 'Гренада: пляжи и водопады',
    description: 'Расслабляющий отдых на Карибах.',
    price: 80000,
    location: 'Америка',
    travelType: 'пляжный',
    images: ['/assets/grenada.jpg'],
  },
  {
    id: 38,
    title: 'Колумбия: Картахена и кафе',
    description: 'Гастрономия и культура Колумбии.',
    price: 85000,
    location: 'Америка',
    travelType: 'гастрономический',
    images: ['/assets/cartagena.jpg'],
  },
  {
    id: 39,
    title: 'Гавайи: вулканы и серфинг',
    description: 'Тур по островам с активными вулканами и серфингом.',
    price: 110000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/hawaii.jpg'],
  },
  {
    id: 40,
    title: 'Флорида: Диснейленд и пляжи',
    description: 'Семейный отдых в парках и на пляже.',
    price: 90000,
    location: 'Америка',
    travelType: 'семейный',
    images: ['/assets/florida.jpg'],
  },
  {
    id: 41,
    title: 'Тринидад и Тобаго: острова и карнавалы',
    description: 'Веселье и экзотика Карибов.',
    price: 100000,
    location: 'Америка',
    travelType: 'культурный',
    images: ['/assets/trinidad.jpg'],
  },
  {
    id: 42,
    title: 'Эквадор: Котопахи и Галапагосы',
    description: 'Путешествие по вулканам и морским островам.',
    price: 140000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/galapagos.jpg'],
  },
  {
    id: 43,
    title: 'Панама: Канал и джунгли',
    description: 'Отдых в экзотических местах и изучение природы.',
    price: 120000,
    location: 'Америка',
    travelType: 'экспедиционный',
    images: ['/assets/panama.jpg'],
  },
  {
    id: 44,
    title: 'Белиз: рифы и археология',
    description: 'Погружение в морские экосистемы и руины цивилизаций майя.',
    price: 130000,
    location: 'Америка',
    travelType: 'экскурсионный',
    images: ['/assets/belize.jpg'],
  },
  {
    id: 45,
    title: 'Коста-Рика: джунгли и волканы',
    description: 'Путешествие по экзотическим лесам и активным вулканам.',
    price: 120000,
    location: 'Америка',
    travelType: 'активный',
    images: ['/assets/costa_rica.jpg'],
  },
];
